### ISSUE TITLE
Help Regarding Dataset.

### ISSUE THREAD

**Issue by saimathura** [scale-lab/MTLoRA#10]
Hi, I am trying to run the model inference. However, I'm currently unable to understand where I must get the dataset. can you please guide me with this?

![image](https://github.com/user-attachments/assets/595b8d71-77ad-49ca-9d75-67e6f45a3bd0)

**Comment by saimathura** [comment]
also, can you guide me on which Swin model variant should I use?

**Comment by ahmed-agiza** [comment]
Hi @saimathura  here is a [link for PASCAL dataset](https://data.vision.ee.ethz.ch/kmaninis/share/MTL/PASCAL_MT.tgz).

The pretrained model weight are also available [here](https://drive.google.com/file/d/1AzzOgX6X0VFKyXUBXhwlgmba5NbPUq3m/view?usp=drive_link), so you don't need to re-train the model if you just want to do eval/inference. The command to run the eval with the pretrained weights is available in the **README**.

We use Swin **tiny** but with img size 448, but you shouldn't need to specify the variant if you use the main configuration file (mtlora_tiny_448_r64_scale4_pertask.yaml) as shown in the README.

**Comment by saimathura** [comment]
Can you also guide me with one more thing, can you tell me where to change the rank in the config file?

Thank you for your time and consideration.

**Comment by ahmed-agiza** [comment]
Hi, there are a couple of ways to change it; the easiest way is through the **R_PER_TASK** key in the config file; within **R_PER_TASK**, you can specify the rank for each task, in addition to a special key **shared** that represents the rank for the shared matrix, refer to the [main config file, line 28](https://github.com/scale-lab/MTLoRA/blob/main/configs/mtlora/tiny_448/mtlora_plus_tiny_448_r64_scale4_pertask.yaml#L28) for reference.

**Comment by saimathura** [comment]
Thank you for your time and patience.
