### ISSUE TITLE
How to calculate deltam

### ISSUE THREAD

**Issue by abhishekammu** [scale-lab/MTLoRA#11]
Can you please tell how is delta m being calculated , is the code doing it or is it being calculated manually after obtaining the results

**Comment by ahmed-agiza** [comment]
Hi @abhishekammu, we compute it manually offline or through a custom Weights & Bias panel that has the baseline values; but you can add it to your codebase if you like (lots of other repositories do that).

**Comment by abhishekammu** [comment]
Sure thank you
