### ISSUE TITLE
Could you provide some settings for hyperparameters, such as WARMUP_LR and MIN_LR?

### ISSUE THREAD

**Issue by HereNowL** [scale-lab/MTLoRA#2]

**Comment by ahmed-agiza** [comment]
Hi @HereNowL, we follow the same structure of Swin, so all the default parameters are set in [config.py](https://github.com/scale-lab/MTLoRA/blob/main/config.py), and overridden by the configuration YAML file you choose. In the config.py file, we set the default WARMUP_LR & MIN_LR to 5e-7 &  5e-6, respectively.

**Comment by HereNowL** [comment]
Could you please provide me with the value of BASE_LR?

**Comment by ahmed-agiza** [comment]
It is also specified in [config.py](https://github.com/scale-lab/MTLoRA/blob/main/config.py) as 5e-4.

**Comment by HereNowL** [comment]
What is the batch size during training? I noticed that there is also a setting for batch size in the main.py.

**Comment by ahmed-agiza** [comment]
We used a batch size of 32, the setting in main.py can be used to override the configuration file.
