### ISSUE TITLE
About TA-LoRA in code?

### ISSUE THREAD

**Issue by zermatt-luo** [scale-lab/MTLoRA#3]
Hello, by running the code you provided, I found that the TA-LoRA mentioned in the paper does not exist in the first N-1 Transformer Blocks in the code, and it seems that there is only TS-LoRA. Is it due to the setting?

**Comment by ahmed-agiza** [comment]
Hi @zermatt-luo, I am not sure if there is a setting that will result in running TS-LoRA only; if you choose one of the configs from the [configs folder](https://github.com/scale-lab/MTLoRA/tree/main/configs/mtlora/tiny_448), you should get the whole setup. If that is not the case, let me know how you are running the code, and I will check. 
Also note that TA-LoRA parameter names follow the typical convention of .lora_A/.lora_B (i.e., you won't see "TS-LoRA" or "TA-LoRA" in the parameter name itself if that's how you are checking).

**Comment by ahmed-agiza** [comment]
The released code actually had a bug related to some missing lora modules, but it should be fixed now. Feel free to re-open if it is still an issue.
