### ISSUE TITLE
Number of trainable parameters

### ISSUE THREAD

**Issue by neerajgangwar** [scale-lab/MTLoRA#5]
Hi @ahmed-agiza!

I am using the `mtlora_tiny_448_r64_scale4_pertask` config to reproduce the main results from the paper (Table 1). While the paper mentions that there are 8.34M trainable parameters with MTLoRA ($r = 64$), the script (`main.py`) prints the following:
```
Number of trainable params: 5,297,210
Decoder params:             1,946,624
LoRA params:                1,751,040
Extra params:                1,599,546
Total params:               31,215,482 (trainable ratio: 16.97%)
Total params without LoRA:  29,464,442 (trainable ratio: 17.98%)
```
I also tried to load the model using command line (outside the script) using the same config and used `mark_only_lora_as_trainable` method to mark selected parameters trainable, I am still getting the same number. I am not sure where this mismatch is coming from. The following is the MTLoRA config:
```
BIAS: none
DOWNSAMPLER_ENABLED: False
DROPOUT: [0.05, 0.05, 0.05, 0.05]
ENABLED: True
FC1_ENABLED: True
FC2_ENABLED: True
FREEZE_PRETRAINED: True
INTERMEDIATE_SPECIALIZATION: False
PROJ_ENABLED: True
QKV_ENABLED: True
R: [64, 64, 64, 64]
R_PER_TASK:
  depth: [4]
  edge: [4]
  human_parts: [4, 4, 4, 4]
  normals: [4, 4, 4, 4]
  sal: [4, 4, 4, 4]
  semseg: [4, 4, 4, 4]
  shared: [64, 64, 64, 64]
R_PER_TASK_LIST: [{'human_parts': 4, 'normals': 4, 'sal': 4, 'semseg': 4, 'shared': 64}, {'human_parts': 4, 'normals': 4, 'sal': 4, 'semseg': 4, 'shared': 64}, {'human_parts': 4, 'normals': 4, 'sal': 4, 'semseg': 4, 'shared': 64}, {'human_parts': 4, 'normals': 4, 'sal': 4, 'semseg': 4, 'shared': 64}]
SCALE_PER_TASK:
  human_parts: [4.0, 4.0, 4.0, 4.0]
  normals: [4.0, 4.0, 4.0, 4.0]
  sal: [4.0, 4.0, 4.0, 4.0]
  semseg: [4.0, 4.0, 4.0, 4.0]
SCALE_PER_TASK_LIST: [{'human_parts': 4.0, 'normals': 4.0, 'sal': 4.0, 'semseg': 4.0}, {'human_parts': 4.0, 'normals': 4.0, 'sal': 4.0, 'semseg': 4.0}, {'human_parts': 4.0, 'normals': 4.0, 'sal': 4.0, 'semseg': 4.0}, {'human_parts': 4.0, 'normals': 4.0, 'sal': 4.0, 'semseg': 4.0}]
SHARED_MODE: matrix
SHARED_SCALE: [4.0, 4.0, 4.0, 4.0]
SPLIT_QKV: False
TASK_SCALE: [4.0, 4.0, 4.0, 4.0]
TRAINABLE_SCALE_PER_TASK: False
TRAINABLE_SCALE_SHARED: False
```

Could you please help identify the issue?

**Comment by ahmed-agiza** [comment]
Hi @neerajgangwar, there might be a bug that happened while we were cleaning up the code for the public release causing running the internal "uncleaned" version gives the right number while the public version is the one that has the issue (my guess is that some configuration is set to a wrong default value); I don't think I can check it today, but let me investigate it over the weekend and tell you the fix, it should be something simple.

**Comment by ahmed-agiza** [comment]
Actually, I found the bug and pushed a fix; just pull, and you should get the correct numbers that are in the papers. Thanks for catching this!

**Comment by neerajgangwar** [comment]
Thanks @ahmed-agiza. The discrepancy in the number of trainable parameters is fixed.
