### ISSUE TITLE
Question about `shared_mode` in the code

### ISSUE THREAD

**Issue by neerajgangwar** [scale-lab/MTLoRA#7]
Hi @ahmed-agiza!
This is unrelated to the default implementation, but I have a question about the `shared_mode` option in the code. While the paper uses `shared_mode=matrix`, I wanted to know more about `shared_mode=addition`. From my understanding, in this case, the shared LoRA in the TS-LoRA modules will not be present, and the sum of the task-specific outputs will be fed into the subsequent stages of Swin Transformer. Could you please share some insights about this mode in case you have experimented with it? How did it perform in comparison to what the paper uses?
Thanks!

**Comment by ahmed-agiza** [comment]
Hi @neerajgangwar
Your understanding is correct; we tested it in the early phase; it was training fine, but performing a bit worse than the current mode so we dropped it, but honestly, we didn't have time to investigate it thoroughly and tune the parameters for it (or try to improve it); it might be different/better than before with the current implementation and configurations, but we didn't have the chance to evaluate it using the current version; but I am skeptical that it will perform better, I think at most it will be close to the current one.

**Comment by neerajgangwar** [comment]
Hi @ahmed-agiza, thanks for the information. Appreciate it!
