### ISSUE TITLE
About batch size and epoch

### ISSUE THREAD

**Issue by CQC-gogopro** [scale-lab/MTLoRA#9]
Excellent work. Could you please provide some detailed settings of the experiment to roughly reproduce your work, such as batch size and number of epochs, to fill in the commands in readme.rm:

python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 main.py --cfg configs/mtlora/tiny_448/<config>.yaml --pascal <path to pascal database> --tasks semseg,normals,sal,human_parts --batch-size <batch size> --ckpt-freq=20 --epoch=<num epochs> --resume-backbone <path to the weights of the chosen Swin variant>

**Comment by ahmed-agiza** [comment]
Hi @CQC-gogopro 
I just posted the weights and updated the batch size (32) in the README.md. We usually train for ~300 epochs, but I recommend just using the pre-trained weights.

**Comment by CQC-gogopro** [comment]
thanks a lot！
